name: Fetch Meteogram Data

on:
  schedule:
    # 8 AM MDT is 14:00 UTC
    - cron: '0 14 * * *'
    # 12 PM MDT is 18:00 UTC
    - cron: '0 18 * * *'
    # 4 PM MDT is 22:00 UTC
    - cron: '0 22 * * *'
  workflow_dispatch:      # Allows manual runs from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change to your Python version if needed

      - name: Install dependencies
        run: |
          pip install pandas
        # Remove this step if you have no requirements.txt

      - name: Run script
        env:
            API_KEY: ${{secrets.API_KEY}}
        run: python fetch_meteodata.py
        
      - name: Commit and push updated meteogram
        run: |
          # Configure git user, this is required to commit
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add Data/meteogram_data.pkl
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/noahcreany/TRMNL_Screens.git HEAD:main
          git push
