name: Build Meteogram

on:
  schedule:
    # Runs hourly between 8:00 and 18:00 UTC. Adjust for your timezone!
    - cron: ''59 13-23,0-1 * * *'
  workflow_dispatch:      # Allows manual runs from the Actions tab


permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change to your Python version if needed

      - name: Install dependencies
        run: |
          pip install -r meteogram_requirements.txt

      - name: Run script
        run: python meteogram.py
        
      - name: Commit and push updated meteogram
        run: |
          # Configure git user, this is required to commit
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add Images/meteogram.png
          git commit -m "Meteogram updated" || echo "No changes to commit"
          git push
